#!/bin/bash

# export CARDS_JASYPT_ENCRYPTOR_PASSWORD="{{ op://work/dotfiles/CARDS_JASYPT_ENCRYPTOR_PASSWORD }}"
export JASYPT_ENCRYPTOR_PASSWORD="{{ op://work/dotfiles/JASYPT_ENCRYPTOR_PASSWORD }}"
export NEXUS_BASE64_AUTH_TOKEN="{{ op://work/dotfiles/NEXUS_BASE64_AUTH_TOKEN }}"
export NEXUS_USER_TOKEN="{{ op://work/dotfiles/NEXUS_USER_TOKEN }}"
export NEXUS_PASS_TOKEN="{{ op://work/dotfiles/NEXUS_PASS_TOKEN }}"
export SPRING_DATA_REDIS_HOST="{{ op://work/dotfiles/SPRING_DATA_REDIS_HOST }}"
export SPRING_DATA_REDIS_PASSWORD="{{ op://work/dotfiles/SPRING_DATA_REDIS_PASSWORD }}"

export NPM_AUTH_TOKEN="_auth=$NEXUS_BASE64_AUTH_TOKEN"
export ORG_GRADLE_PROJECT_nexusUsername="$NEXUS_USER_TOKEN"
export ORG_GRADLE_PROJECT_nexusPassword="$NEXUS_PASS_TOKEN"
