#!/bin/bash

eval "$(op inject --in-file "${HOME}/.secrets")"

case $- in
  *i*) ;;
  *) return ;;
esac

export HISTCONTROL=erasedups:ignoredups:ignorespace
export HISTSIZE=100000
export HISTFILESIZE=100000

shopt -s histappend
shopt -s checkwinsize

export VISUAL=nvim
export EDITOR=nvim
export SVN_EDITOR=nvim

source "$HOME/.bash_aliases"
source "$HOME/.bash_functions"

export PS1="\[\e[32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "

bind '"\e[A": history-substring-search-backward'
bind '"\e[B": history-substring-search-forward'
bind '"\C-H": backward-kill-word'

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  source /etc/bash_completion
fi

if [ -d "$HOME/bin" ]; then
  export PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "/usr/local/go/bin" ]; then
  export PATH="/usr/local/go/bin:$PATH"
fi

if [ -d "$HOME/.local/share/JetBrains/Toolbox/scripts" ]; then
  export PATH="$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH"
fi

if [ -d "$HOME/.cargo" ]; then
  source "$HOME/.cargo/env"
fi

if [ -d "$HOME/.sdkman" ]; then
  export SDKMAN_DIR="$HOME/.sdkman"
  export GRADLE_COMPLETION_UNQUALIFIED_TASKS="true"
  source "$HOME/.sdkman/bin/sdkman-init.sh"
fi

if [ -d "$HOME/.local/share/fnm" ]; then
  export FNM_PATH="$HOME/.local/share/fnm"
  export PATH="$FNM_PATH:$PATH"
  eval "$(fnm env --use-on-cd --corepack-enabled --version-file-strategy=recursive --resolve-engines --shell bash)"
  eval "$(fnm completions --shell bash)"
fi

if [ -e "$HOME/.bash_completion.d/gradle-completion.bash" ]; then
  source "$HOME/.bash_completion.d/gradle-completion.bash"
fi

export AZURE_DEV_COLLECT_TELEMETRY="no"
export COREPACK_ENABLE_AUTO_PIN=0
export PNPM_HOME="/home/pcbowers/.local/share/pnpm"
export PATH="$HOME/.local/share/pnpm:$PATH"
export PATH="$HOME/go/bin:$PATH"

eval "$(starship init bash)"

eval "$(zoxide init bash)"
