#!/bin/bash

# cd
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
alias work='cd $HOME/work'
alias play='cd $HOME/play'

# ls
alias ls='lsd'
alias ll='lsd -l'
alias la='lsd -A'
alias lla='lsd -lA'

# cat
alias cat='bat --paging=never'

# grep
alias grep='rg'

# git
alias gs='git status'
alias ga='git add -A'
alias gp='git pull'
alias gf='git fetch'

# Ubuntu Specific
alias upup='sudo apt update && sudo apt upgrade'
alias clean='sudo apt autoremove'
alias ifconfig='ip addr show'
alias ge='gnome-text-editor'

# pnpm
alias p='pnpm'

# Gradle
alias gradlew='./gradlew'

# Easy Source When Making Edits
alias sf='source $HOME/.bashrc'

# Add an alert alias for long running commands
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
