#!/bin/bash

# Always List Directory After 'cd'
cd() {
  builtin cd "$@" && ls
}

# Get the Weather
weather() {
  curl "wttr.in?format=$1"
}

# Compresses a video file
compress() {
  ffmpeg -i "$1" -vcodec libx264 -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -r 24 -y -an "$(basename "$1" | sed 's/\.[^.]*$//')-compressed.mp4"
}

# List Directory Contents as a Tree
tree() {
  lsd -A --tree --depth ${1:-2}
}

# Reboot a Spring app on changes
gradledev() {
  ./gradlew build --continuous --quiet -xtest -xdockerRun > /dev/null 0>&1 2>&1 &
  ./gradlew bootRun
  kill "$(jobs -p)"
}

# Extract Files
extract() {
  if [ -z "$1" ]; then
    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
  else
    if [ -f $1 ]; then
      case $1 in
        *.tar.bz2) tar xvjf $1 ;;
        *.tar.gz) tar xvzf $1 ;;
        *.tar.xz) tar xvJf $1 ;;
        *.lzma) unlzma $1 ;;
        *.bz2) bunzip2 $1 ;;
        *.rar) unrar x -ad $1 ;;
        *.gz) gunzip $1 ;;
        *.tar) tar xvf $1 ;;
        *.tbz2) tar xvjf $1 ;;
        *.tgz) tar xvzf $1 ;;
        *.zip) unzip $1 ;;
        *.Z) uncompress $1 ;;
        *.7z) 7z x $1 ;;
        *.xz) unxz $1 ;;
        *.exe) cabextract $1 ;;
        *) echo "extract: '$1' - unknown archive method" ;;
      esac
    else
      echo "$1 - file does not exist"
    fi
  fi
}
